### ISSUE TITLE
Doesn't parse #EXT-X-MAP attribute in m3u8

### ISSUE THREAD

**Issue by denex** [globocom/m3u8#102]
Some playlists contain #EXT-X-MAP:URI="fileSequence0.mp4" and this attribute doesn't processed.

>    The EXT-X-MAP tag specifies how to obtain the Media Initialization
>    Section (Section 3) required to parse the applicable Media Segments.
>    It applies to every Media Segment that appears after it in the
>    Playlist until the next EXT-X-MAP tag or until the end of the
>    playlist.
> 
>    Its format is:
> 
>    #EXT-X-MAP:<attribute-list>

https://tools.ietf.org/html/draft-pantos-http-live-streaming-21#section-4.3.2.5

**Comment by leandromoreira** [comment]
https://github.com/globocom/m3u8/pull/103#pullrequestreview-32380019
