### ISSUE TITLE
#EXT-X-MAP:URI and #EXT-X-PROGRAM-DATE-TIME ignored in dump

### ISSUE THREAD

**Issue by mfojtak** [globocom/m3u8#109]
The **#EXT-X-PROGRAM-DATE-TIME** is ignored when dumping m3u8 object to string.

Also the segment level **#EXT-X-PROGRAM-DATE-TIME** is ignored.
The global one gets dumped ok.

**Comment by mauricioabreu** [comment]
Thank you for the effort to open this issue.
Yes, I guess it is a bug. I just opened a pull request to deal with it: https://github.com/globocom/m3u8/issues/109

**Comment by mauricioabreu** [comment]
We will release this bugfix in the next version. Thanks again for contributing to this project.
