### ISSUE TITLE
how to sort the playlists

### ISSUE THREAD

**Issue by alochym01** [globocom/m3u8#117]
`
#EXTM3U

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=160000,RESOLUTION=192x144
https://newsabc.com/144.m3u8?v=e0ae030e

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1693333,RESOLUTION=1280x720
https://newsabc.com/720.m3u8?v=e0f76255

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1000000,RESOLUTION=640x480
https://newsabc.com/480.m3u8?v=ac8970e9

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=506666,RESOLUTION=480x360
https://newsabc.com/360.m3u8?v=a8b878db

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=213333,RESOLUTION=320x240
https://newsabc.com/240.m3u8?v=35f25da0
`

how to sort the playlists in order desc

thank you

**Comment by leandromoreira** [comment]
I think you can rely on python's power:

```python
variant_m3u8 = m3u8.loads('#EXTM3U8 ... contains a variant stream ...')
# sort by bandwidth
sorted(student_tuples, key=lambda playlist: playlist.stream_info.bandwidth)
```
