### ISSUE TITLE
Parsing extended #EXTINF tags

### ISSUE THREAD

**Issue by hsahovic** [globocom/m3u8#123]
### Context

According to [Wikipedia](https://en.wikipedia.org/wiki/M3U), m3u is a _de facto_ standard, which implies that its implementation might vary across different platforms, software or use cases.

In particular, I have recently been confronted with a couple of implementations that are not compliant with [this spec](https://tools.ietf.org/html/draft-pantos-http-live-streaming-20), which seems to be this repo's reference.

[Here](https://siptv.eu/howto/playlist.html) and [here](https://wiki.tvip.ru/en/m3u) are two simple descriptions of such implementations, and here is an extract of such a m3u8 file :
```
#EXTM3U
#EXTINF:-1 tvg-id="Be1.be" tvg-name="Be1 Alt" group-title="News" parent-code="1234" audio-track="nl",Be1 Name
http://channel.stream.address/to_be_placed/on_separate_line/123.ts
```

### Proposed addition to the parser

**Adding a parser option allowing to parse these extended tags and retrieve them in segments.**

I can fork the project and create a pull request implementing this feature, but I would like to make sure that it fits with the project's orientation.

**Comment by leandromoreira** [comment]
Nice @hsahovic but how do you think to add this extension points? like passing extra functions/classes?  (can you express your ideas with simple example code? like...)
```python
class VariantParser:
    def parse(args):
        return "something"

my_parser = VariantParser()

m3u8_obj = m3u8.load('http://videoserver.com/playlist.m3u8', variant_pipeline=[my_parser])
```

@flavioribeiro is a pythonista and maybe he can help us here too.

**Comment by hsahovic** [comment]
@leandromoreira I was thinking of modifying the `parse` function's signature from:

```python
def parse(content, strict=False)
``` 

To something along the lines of:

```python
def parse(content, strict=False, accept_extended_tags=False)
```

The default behavior of the function would remain the same, but with `accept_extended_tags` set to `True`,  a script such as 

```python
from m3u8 import parse

content = """#EXTM3U
#EXTINF:-1 tvg-id="Be1.be" parent-code="1234",Be1 Name
http://channel.stream.address/to_be_placed/on_separate_line/123.ts"""

# Prints content's first segment
print(parse(content)['segments'][0])
```

would print `{'title': 'Be1 Name', 'duration': -1.0, 'cue_out': False, 'uri': 'http://channel.stream.address/to_be_placed/on_separate_line/123.ts', 'discontinuity': False, 'extended_extinf_tags' : {'tvg-id': 'Be1.be', 'parent-code': '1234'}}` instead of rising a `ValueError` as it does now.

As far as I can tell, this would mainly imply a couple of minor modifications to `parse` and `_parse_extinf` and adding a couple tests.

**Comment by leandromoreira** [comment]
Nice, I'm okay with that! :) we can let `strict=False` as the default value.

**Comment by norok2** [comment]
@hsahovic any progress on this?

**Comment by norok2** [comment]
@leandromoreira would you be OK with adding `pyparsing` as a dependency? that would make the parsing of exteded `#EXTINF` so much simpler...

**Comment by leandromoreira** [comment]
@norok2 I'm ok with new dependencies but I'd like to listen to @flavioribeiro or @hltbra or any other project member on that matter. 

@norok2 what would be the `pyparsing` usage?

**Comment by norok2** [comment]
@leandromoreira 

This for example would do the trick:

    # ======================================================================
    def parse_extinf_extras(text):
        """
        Parse m3u/m3u8's EXTINF extra parameters.

        Args:
            text (str): EXTINF to be parsed.

        Returns:
            parsed (dict): Result of the parsing.

        Examples:
            >>> text = 'tvg-id="ciao pippo" tvg-name="some name of some kind -- this is so true" tvg-logo="" group-title="the true group title is?"'
            >>> parse_name(text)
        """
        g_sep = pp.Literal(' ').suppress()
        kv_sep = pp.Literal('=').suppress()
        hyphen = ('-')
        value = pp.quotedString.setParseAction(pp.removeQuotes)
        key = pp.Word(pp.alphanums + hyphen)
        key_value = pp.Group(key + kv_sep + value)
        exp = pp.Dict(pp.OneOrMore(key_value))

        try:
            parsed = exp.parseString(text)
            result = parsed.asDict()
        except pp.ParseException:
            result = None
        return result

**Comment by leandromoreira** [comment]
Reading the [official documentation](https://tools.ietf.org/html/draft-pantos-http-live-streaming-23#section-4.3.2.1):

> 4.3.2.1.  EXTINF
> 
>    The EXTINF tag specifies the duration of a Media Segment.  It applies
>    only to the next Media Segment.  This tag is REQUIRED for each Media
>    Segment.  Its format is:
> 
>    #EXTINF:<duration>,[<title>]
> 
>    where duration is a decimal-floating-point or decimal-integer number
>    (as described in Section 4.2) that specifies the duration of the
>    Media Segment in seconds.  Generally, durations SHOULD be decimal-
>    floating-point, with enough accuracy to avoid perceptible error when
>    segment durations are accumulated.  If the compatibility version
>    number is less than 3, durations MUST be integers.  Durations that
>    are reported as integers SHOULD be rounded to the nearest integer.
>    The remainder of the line following the comma is an optional human-
>    readable informative title of the Media Segment expressed as raw
>    UTF-8 text.

It didn't specify what you can do at `title field` but once we implement this way we're going to assume that this format `"#EXTINF:-1 tvg-id="Be1.be" tvg-name="Be1 Alt"..."` is genereally used.

My question, is it common to use metadata over title using space separated with fields following the pattern `key=value`?  If yes, who's doing it? If not, it wouldn't be easier if we just provide hooks (pre_parser, after_parser) so each user can extend to its usage?

**Comment by norok2** [comment]
I would have no clue about the usage frequency. I guess it depends on the application that you use. Just a side note: your "official" documentation refers to the HTTP Live Streaming (HLS) which is an extension of the UTF-8 version of `m3u`, namely `m3u8`. There is no official documentation for `m3u`/`m3u8`.

Regarding the line to parser. That is actually:

    #EXTINF:<DURATION> [<KEY>="<VALUE>"]*,<TITLE>

What I found annoying of the current implementation is not that it does not read key-value pairs, but rather that it fails to parse when they are present. If your target files are HLS, I guess there is no need for changing the codebase, but if your goal is to support at least common usages of `m3u` / `m3u8`, you should consider a more robust implementation, one that is not failing in the aforementioned case, to the least. For example, VLC seems to be fully supporting this extended syntax.

**Comment by leandromoreira** [comment]
This lib tries to cover only the `m3u8 for HTTP Live Streaming (HLS)`.

**Comment by norok2** [comment]
OK, then I would actually suggest you to update your docs to reflect that. Also, if you would not be willing to add the support for the extra tag, I'll probably write / fork this to a more robust implementation that is not limited to HLS.

**Comment by leandromoreira** [comment]
I don't mean to be rude but is within the project description.

![screen shot 2018-12-15 at 9 11 11 pm](https://user-images.githubusercontent.com/55913/50048241-edc58d80-00ad-11e9-983b-0642c78848b2.png)

>  Also, if you would not be willing to add the support for the extra tag

Yes but maybe through extension points.

**Comment by flavioribeiro** [comment]
I don't see  a big case in favor of adding `pyparsing`. If we'd add this dependency, we'd need to use it in all text parsing across the library to keep consistency. 

I'm wondering if it would work better to receive a `custom_tags_func` as the optional parameter on https://github.com/globocom/m3u8/blob/master/m3u8/parser.py#L39 and call it on each [line iteration](https://github.com/globocom/m3u8/blob/master/m3u8/parser.py#L64) passing the line, the `data` and `state` objects. This would enable extensions to be written outside the library and give @norok2 the ability to add their own dependencies and custom code. 

Maybe better than that would be to promote `parse` to class and expose it for custom classes to inherit enabling it to parse some tags supersets? Just thinking out loud. :)

**Comment by flavioribeiro** [comment]
refs #124

**Comment by mauricioabreu** [comment]
@hsahovic does the change in #130 helps you?

**Comment by cbaurtx** [comment]
Hello,

I tried to use custom tags as you proposed to hsahovic and had no luck:
Test m3u:
#EXTM3U
#EXTINF:-1 tvg-id="ARD.de" tvg-logo="ard.png",ARD

Issues:
1. The tag #EXTM3U was sent to my custom parse function. Why?
2. When loading the m3u there is an error and the custom parse function is not called:
   ValueError: could not convert string to float: '-1 tvg-id="ARD.de" tvg-logo="ard.png"' 

It seems that hsahovic threw the towel. I am with you on keeping dependencies to a minimum.
Would it be OK to use the regular expressions module? If that is the case I could give it a try.

**Comment by mauricioabreu** [comment]
Hey, thanks for the report @cbaurtx 

Answering:

1 - It retrieves the `#EXTM3U` because it starts with `#`. You can ignore it on your side. But if you have any idea, I would be glad to listen to.
2 - It seems to be an error. I noticed you opened a new PR to fix it. I will check it later. Thank you!

**Comment by hsahovic** [comment]
@cbaurtx Hi ! Sorry for not responding earlier. I ended up using a private fork that implemented this:

> @leandromoreira I was thinking of modifying the `parse` function's signature from:
> 
> ```python
> def parse(content, strict=False)
> ```
> 
> To something along the lines of:
> 
> ```python
> def parse(content, strict=False, accept_extended_tags=False)
> ```
> 
> The default behavior of the function would remain the same, but with `accept_extended_tags` set to `True`, a script such as
> 
> ```python
> from m3u8 import parse
> 
> content = """#EXTM3U
> #EXTINF:-1 tvg-id="Be1.be" parent-code="1234",Be1 Name
> http://channel.stream.address/to_be_placed/on_separate_line/123.ts"""
> 
> # Prints content's first segment
> print(parse(content)['segments'][0])
> ```
> 
> would print `{'title': 'Be1 Name', 'duration': -1.0, 'cue_out': False, 'uri': 'http://channel.stream.address/to_be_placed/on_separate_line/123.ts', 'discontinuity': False, 'extended_extinf_tags' : {'tvg-id': 'Be1.be', 'parent-code': '1234'}}` instead of rising a `ValueError` as it does now.
> 
> Similar arguments could be added to `load`, `loads` and `M3U8`'s` __init__`.
> 
> As far as I can tell, this would mainly imply a couple of minor modifications to `parse` and `_parse_extinf` and adding a couple tests.

Unfortunately, I do not have access to the source anymore as it was hosted on my ex-employer's repo system.
It was implemented using `re`.
