### ISSUE TITLE
Basic support for custom tags

### ISSUE THREAD

**Issue by tausackhn** [globocom/m3u8#124]
Sometimes services add custom tags that they use for their own purposes. Custom tags are also started with `#EXT`. Applications are going to ignore them as it is written in RFC8216. But these tags can be also helpful depending on service. Currently, the library ignores custom tags recognizing them as a comment.
What do you think about saving custom tags started with `#EXT` somewhere in the model? Or specifing additional protocols for `parser` function?

**Comment by mauricioabreu** [comment]
Closed via #130

**Comment by mauricioabreu** [comment]
Hey @tausackhn can you tell us if the change we recently made does what you needed, please?

**Comment by tausackhn** [comment]
@mauricioabreu thank you. It covers my needs.
