### ISSUE TITLE
这是直播源吗？

### ISSUE THREAD

**Issue by TDcloud** [globocom/m3u8#131]
具体怎么使用有视频演示的demo吗

**Comment by mauricioabreu** [comment]
Thank you for opening this issue.
Unfortunately, `Google translator` could not make a good translation of what you said. Could you please update your issue using english?

**Comment by TDcloud** [comment]
> 感谢您解决此问题。
> 不幸的是，`Google translator`无法对你所说的内容做出很好的翻译。你能用英语更新你的问题吗？

How to use demo with video demonstration?

**Comment by mauricioabreu** [comment]
What are you trying to achieve? Sorry but what do you mean by "demo"?

**Comment by mauricioabreu** [comment]
Closed.
Reason: lack of feedback.
