### ISSUE TITLE
how can i kown this m3u8 file's duration?  'target_duration' seems not it's real duration

### ISSUE THREAD

**Issue by SuperTommy007** [globocom/m3u8#136]

**Comment by SuperTommy007** [comment]
![_122](https://user-images.githubusercontent.com/36689187/53949823-d5419e00-4105-11e9-9a02-141b560a1873.png)
m3_u8_obj = m3u8.load(r'https://livenging.alicdn.com/mediaplatform/62ad0659-a8b9-4603-958b-f4034215327d_merge.m3u8')
# print(m3_u8_obj.__dict__)
# print(m3_u8_obj.data)
print(m3_u8_obj.data.get('targetduration'))  
17.0

**Comment by leandromoreira** [comment]
For live content you must multiply the `targetduration` by the amount of segments you have.

**Comment by mauricioabreu** [comment]
Maybe a good feature could be a `property` with this information. It would work for live and VOD playlists.

```python
@property
def playlist_duration(self):
    return len(self.segments) * self.target_duration
```

**Comment by mauricioabreu** [comment]
We could add this property but for `live` playlists it would make less sense. Right?

**Comment by leandromoreira** [comment]
I don't think we should add any particular property for a live, ideally that property should be available at both kinds of streaming: vod and live. Besides this is easy to calculate, I'm leaning towards to close this issue and move one.

**Comment by mauricioabreu** [comment]
@leandromoreira me too. This is easy to calculate on the side of the users.

**Comment by mauricioabreu** [comment]
side-note: that property would be useful both to live and VOD but it would make more sense to VOD because live playlists don't have an ending time.

**Comment by SuperTommy007** [comment]
@leandromoreira @mauricioabreu yeah you are right,thanks for answer my question,and i try to calculate it's duration use len(self.segments) * self.target_duration and the result seems a little longer than its real duration ,whatever thank you for your replys

**Comment by SuperTommy007** [comment]
`m3_u8_obj = m3u8.load(r'https://livenging.alicdn.com/mediaplatform/343e7e75-ff67-423d-b732-8ca36219697e_merge.m3u8')

print(sum(i.get('duration') for i in m3_u8_obj.data.get('segments')) / 3600
4.342851666666611`
this result is more close to the real duration

**Comment by mauricioabreu** [comment]
@SuperTommy007 glad you get it working!

**Comment by elinaldosoft** [comment]
I created this method 
```
def duration_by_url(url: str) -> int:
    try:
        playlist = m3u8.load(url)
        if playlist.playlists:
            return duration_by_url(playlist.playlists[0].absolute_uri)
        return int(sum(x.duration for x in playlist.segments))
    except Exception:
        return 0
 ```

**Comment by theoctober19th** [comment]
@elinaldosoft Works like charm. Thanks!

**Comment by jakebrinkmann** [comment]
@elinaldosoft  thank you so much, worked out-of-the-box ❤️ 

```python
>>> seconds = duration_by_url('https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8')
>>> str(datetime.timedelta(seconds=seconds))
  '0:10:34'
```
