### ISSUE TITLE
Add PDT tag to segment wihtout DISCONTINUITY tag being True.

### ISSUE THREAD

**Issue by rahulsai2341** [globocom/m3u8#141]
I noticed a small discrepancy between the doc and the code. In `model.py`, the PDT(Program-Date-Time) tag for a **segment** is added only when the DISCONTINUITY tag is set to TRUE. This can be found in the method `dump` of class `segment`. 

I think these should be independent of each other? The only relation that I could find between them is that if server provides PDT tags, then it must add PDT tags to all the segments which have DISCONTINUITY tags.

**Comment by mauricioabreu** [comment]
Does https://github.com/globocom/m3u8/pull/142 solve your problem @rahulsai2341 ?

**Comment by rahulsai2341** [comment]
Awesome. Yes it solves my issue. May I know when you would be releasing this into pip? @mauricioabreu

**Comment by mauricioabreu** [comment]
@rahulsai2341 today!

**Comment by mauricioabreu** [comment]
@rahulsai2341 released under `0.3.10` Thank you for the report.
