### ISSUE TITLE
helper function to download the video

### ISSUE THREAD

**Issue by Freakwill** [globocom/m3u8#144]
I just want to download the video instead to know the details of m3u8. Dose the module provide a helper to download and save the video to the local direction, as `download('***.m3u8')` or `m3u8_obj.download`.

**Comment by mauricioabreu** [comment]
Hello!

No, this library is used to parse `m3u8` content. To download videos from `m3u8` files you can go with [youtube-dl](https://github.com/ytdl-org/youtube-dl)
