### ISSUE TITLE
spelling mistake

### ISSUE THREAD

**Issue by Luro02** [globocom/m3u8#162]
Very minor complaint, but shouldn't this line be called `PLAYLIST_WITH_ENCRYPTED_SEGMENTS`?
https://github.com/globocom/m3u8/blob/17b81a37309ed3de1214a8feb7ef878a435b9e86/tests/playlists.py#L74

**Comment by mauricioabreu** [comment]
Thanks for opening this issue. Can you fix it and open a pull request?
We would be very very happy to merge it. 😄

**Comment by mauricioabreu** [comment]
Closed via #167
