### ISSUE TITLE
Add SOCKS4/5, HTTPS proxy support

### ISSUE THREAD

**Issue by uenro** [globocom/m3u8#182]
Is there a way to download a bunch of m3u8 playlists from website using proxy?
I didn't find any suitable method for it in m3u8 parser.

**Comment by leandromoreira** [comment]
doesn't it work with system wide proxy?

**Comment by uenro** [comment]
I think yes but I have several multithreading instances that's why there're more than one requests for downloading m3u8 playlists and using systemwide proxy can't solve this problem

**Comment by Nado15** [comment]
Yeah I agree to that, a feature where we can set a proxy would be nice

**Comment by mauricioabreu** [comment]
@Nado15 @uenro 
master branch has a feature to use your own client to do it. Or you can setup the default HTTP client with `proxies`.

https://github.com/globocom/m3u8#playlists-behind-proxies

**Comment by mauricioabreu** [comment]
I will reopen this issue if it does not satisfy your requirements.

**Comment by Nado15** [comment]
Awesome! Thank you for adding that!
