### ISSUE TITLE
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>

### ISSUE THREAD

**Issue by shahinesi** [globocom/m3u8#186]
```
import m3u8

m3u8_obj = m3u8.load('https://cdn1live.irib.ir/live-channels/smil:tv3/playlist.m3u8?s=3Kj2P7XiASXNg39jL84NZQ&t=1576966822')  # this could also be an absolute filename
print (m3u8_obj.segments)
print (m3u8_obj.target_duration)
```

**`URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>`**

Plz Help me
whats wrong?

**Comment by mauricioabreu** [comment]
I guess your certificate is not fully valid.

It is not expired but it looks like your certificate needs an intermediate/chain to have a trusted root certificate.

If you still want to use HTTPS, you can load your playlist passing `verify_ssl` to `False`.

Example:

```python
import m3u8

playlist = m3u8.load("https://example.com/my_playlist.m3u8", verify_ssl=False)
```

**Comment by shahinesi** [comment]
> I guess your certificate is not fully valid.
> 
> It is not expired but it looks like your certificate needs an intermediate/chain to have a trusted root certificate.
> 
> If you still want to use HTTPS, you can load your playlist passing `verify_ssl` to `False`.
> 
> Example:
> 
> ```python
> import m3u8
> 
> playlist = m3u8.load("https://example.com/my_playlist.m3u8", verify_ssl=False)
> ```

Tnx This Link For Iranian Tv!
But  Return **None** 
Why?

**Comment by mauricioabreu** [comment]
I tried it here and I got a **403 forbidden**. Is there some kind of geoblocking?

**Comment by leandromoreira** [comment]
or authentication / authorization needed

**Comment by mauricioabreu** [comment]
@leandromoreira good catch!

Let's wait for @shahinesi answer. I'm curious about the problem behind it.

**Comment by shahinesi** [comment]
> I tried it here and I got a **403 forbidden**. Is there some kind of geoblocking?

its token **?s=3Kj2P7XiASXNg39jL84NZQ&t=1576966822'**
get [](https://www1.live.irib.ir/?idc=32&idt=tv&idv=19)
![image](https://user-images.githubusercontent.com/16535600/71337202-c8404f00-255f-11ea-8e33-c52d77626b6c.png)

**Comment by mauricioabreu** [comment]
Ok, I found the problem.

You are trying to load a variant playlist. It is a playlist containing the media playlists, with their specific resolutions, bandwidth and URI to get the streams.

```python
>> url = "https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8?s=fOA8xkX-rchTE_Pk1KzqDw&t=1577108537"
>> playlist = m3u8.load(url, verify_ssl=False) # You need the "verify_ssl" set to "False" because your certificate is not fully valid
>> playlist.playlists[0].uri
'chunklist_b307200_slFa.m3u8?s=fOA8xkX-rchTE_Pk1KzqDw&t=1577108537'
```

More info here: https://github.com/globocom/m3u8#variant-playlists-variable-bitrates

**Comment by shahinesi** [comment]
> Ok, I found the problem.
> 
> You are trying to load a variant playlist. It is a playlist containing the media playlists, with their specific resolutions, bandwidth and URI to get the streams.
> 
> ```python
> >> url = "https://cdn1live.irib.ir/live-channels/smil:nasim/playlist.m3u8?s=fOA8xkX-rchTE_Pk1KzqDw&t=1577108537"
> >> playlist = m3u8.load(url, verify_ssl=False) # You need the "verify_ssl" set to "False" because your certificate is not fully valid
> >> playlist.playlists[0].uri
> 'chunklist_b307200_slFa.m3u8?s=fOA8xkX-rchTE_Pk1KzqDw&t=1577108537'
> ```
> 
> More info here: https://github.com/globocom/m3u8#variant-playlists-variable-bitrates

How do I stream this list?
Also is this library capable of separating audio from the HLS?
For speech recognition


tnx for erly answer

**Comment by mauricioabreu** [comment]
> How do I stream this list?

Sorry, I don't get what you mean. To stream this list, you need to follow the README.md

> Also is this library capable of separating audio from the HLS?
No. This library is just a m3u8 parser.
You can use ffmpeg to this kind of job.

**Comment by shahinesi** [comment]
> > How do I stream this list?
> 
> Sorry, I don't get what you mean. To stream this list, you need to follow the README.md
> 
> > Also is this library capable of separating audio from the HLS?
> > No. This library is just a m3u8 parser.
> > You can use ffmpeg to this kind of job.

I mean, this HLS Display in Python
and used ffmpeg for hls video to wav stream

**Comment by mauricioabreu** [comment]
@shahinesi This library only parses m3u8 playlists.
After parsing a playlist, you will end up with all the necessary data to run it through VLC, clappr, hls.js or any other player that supports playing m3u8 playlists.

**Comment by mauricioabreu** [comment]
https://github.com/globocom/m3u8#variant-playlists-variable-bitrates

Here is a documentation on how to read the variant playlist. You can use the `uri` to parse the media playlist.
