### ISSUE TITLE
Remove Expiry from m3u8 link

### ISSUE THREAD

**Issue by luvhighx** [globocom/m3u8#187]
Hi Team,
I have m3u8 links, that will expire every24 hrs. Is there any way to remove or exceed expiry date from m3u8 link.
https://sony247channels.akamaized.net/hls/live/2004802/SONYTEN1HD/hdntl=exp=1578104416~acl=%2f*~data=hdntl~hmac=67b9e05bef106c8545b03dfbbb129d66a50eeb0cada2d438497951ec2bde97cf/master_3868.m3u8

**Comment by leandromoreira** [comment]
nope
