### ISSUE TITLE
Why "For unencrypted segments, the initial key would be None"?

### ISSUE THREAD

**Issue by xuzheliang135** [globocom/m3u8#195]
When I read the code,I find the comment “For unencrypted segments, the initial key would be None”.
What is this feature for? When I work with a m3u8, I expect  unencrypted segments return keys as a empty list. (Because I use `for key in keys` to execute, in this case `[None]` is really annoying).

**Comment by mauricioabreu** [comment]
Here is the full answer: https://github.com/globocom/m3u8#encryption-keys

tl;dr: you can have multiple keys.
