### ISSUE TITLE
How to output m3u8 object to m3u8 file?

### ISSUE THREAD

**Issue by liuyug** [globocom/m3u8#205]
It can parse m3u8 file, but how to output?

**Comment by mauricioabreu** [comment]
What do you mean by "output"? Can you give me an example?

**Comment by leandromoreira** [comment]
You just need to use the dump function https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L344

**Comment by liuyug** [comment]
Yes, It's the function, dump. Thanks.
I do not found any documents, so I miss it?

**Comment by mauricioabreu** [comment]
@liuyug you are right, there is no documentation for this. I juste pushed a new pull request to cover it. Thank you!
