### ISSUE TITLE
about #EXTINF

### ISSUE THREAD

**Issue by liuyug** [globocom/m3u8#206]
I have checked "HTTP Live Streaming" protocol that is said the format is ```#EXTINF:<duration>,[<title>]```. Your library follow it. 

But I found many M3U instance which format is ```#EXTINF:-1 tvg-id="" ....``` from https://github.com/iptv-org/iptv

May you give me advice how to load and process them?

**Comment by SerhiyRomanov** [comment]
I'm faced with the same issue - I am trying to parse a playlist from my IPTV provider and it contains lines like this 
```
#EXTINF:-1 timeshift="7" catchup-days="7" catchup-type="flussonic-ts" tvg-id="first"  group-title="Common folder" tvg-logo="http://pl.myiptv.tv:80/icon/9195.png",First Channel
http://str04.myiptv.tv/9195/mpegts?username=user&password=password&token=token&ch_id=70&req_host=pkjX3BL
```

I don't find any words about this tags here https://tools.ietf.org/html/rfc8216#section-4.3.2.1

Implementation of parsing these tags seems not very complicated, but would it be acceptable?

**Comment by leandromoreira** [comment]
I think you can use https://github.com/globocom/m3u8#custom-tags

**Comment by liuyug** [comment]
got it. Thank you
