### ISSUE TITLE
Problem installing package in anaconda

### ISSUE THREAD

**Issue by fervenceslau** [globocom/m3u8#208]
conda install -c auto m3u8

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - m3u8

Current channels:

  - https://conda.anaconda.org/auto/win-64
  - https://conda.anaconda.org/auto/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by leandromoreira** [comment]
m3u8 is available at https://pypi.org/project/m3u8/0.6.0/ 

I don't know conda, but I think you can either: 

* pip install m3u8
* conda install --use-local m3u8

**Comment by fervenceslau** [comment]
Tried `.\m3u8-master>pip install setup.py` and got these errors:
ERROR: Could not find a version that satisfies the requirement setup.py (from versions: none)
ERROR: No matching distribution found for setup.py

With the conda version, I get the same problem as in the previous post.

However with just `pip install m3u8` it downloads all dependencies:
pip install m3u8
Collecting m3u8
  Downloading m3u8-0.6.0-py3-none-any.whl (20 kB)
Collecting iso8601
  Downloading iso8601-0.1.12-py2.py3-none-any.whl (12 kB)
Installing collected packages: iso8601, m3u8
Successfully installed iso8601-0.1.12 m3u8-0.6.0

I guess it might be an issue with `iso8601`

**Comment by leandromoreira** [comment]
after you installed `pip install m3u8` it should be available foor you to use: try to use it from a python repl.

**Comment by fah** [comment]
In Jupyter(via Anaconda) I tried:
```
!pip install m3u8
import m3u8
```

​Result:
```
Requirement already satisfied: m3u8 in /Users/xyz/opt/anaconda3/lib/python3.9/site-packages (1.0.0)
Requirement already satisfied: iso8601 in /Users/xyz/opt/anaconda3/lib/python3.9/site-packages (from m3u8) (1.0.2)

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-2-692350c40945> in <module>
      1 get_ipython().system('pip install m3u8')
----> 2 import m3u8

ModuleNotFoundError: No module named 'm3u8'
```

m3u8 is the only library that I can not install with "!pip".

**Comment by mauricioabreu** [comment]
Which operating system are you using @fah ? So I can reproduce the bug using a container system

**Comment by fah** [comment]
That's on a Mac with 11.6.5 Big Sur. Thank you!

**Comment by mauricioabreu** [comment]
Sorry for taking so long @fah 
I could not reproduce the problem, even using an Anaconda docker container

```
(base) root@5516ffb00103:/# pip install m3u8
Collecting m3u8
  Downloading m3u8-3.0.0-py3-none-any.whl (24 kB)
Collecting iso8601
  Downloading iso8601-1.0.2-py3-none-any.whl (9.7 kB)
Installing collected packages: iso8601, m3u8
Successfully installed iso8601-1.0.2 m3u8-3.0.0
```

**Comment by mauricioabreu** [comment]
In case you still have problems downloading m3u8, reopen this issue please
