### ISSUE TITLE
frame rate should be rounded to 3 decimal places

### ISSUE THREAD

**Issue by thenewguy** [globocom/m3u8#216]
Per https://tools.ietf.org/html/draft-pantos-hls-rfc8216bis-07#page-41

Should probably use `'FRAME-RATE=%.3g' % self.frame_rate` instead of `'FRAME-RATE=%.5g' % self.frame_rate` at https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L915

**Comment by leandromoreira** [comment]
Agreed.

**Comment by mauricioabreu** [comment]
Thank you @thenewguy
