### ISSUE TITLE
Add full unicode support

### ISSUE THREAD

**Issue by lchiocca** [globocom/m3u8#229]
I know this is a bit wage, but here is my use-case. I'm still using Python 2.7 (I know I should upgrade at some point). I have downloaded a multi-playlist m3u8 file that was encoded as utf-8. I first loaded the file into a string decoding it as utf-8. So I have a unicode string containing the m3u8 data. Parsing it works without any issue. The issue is when converting the m3u8 object back into a string (m3u8.dumps()). A lot of times (in the model.py) there are explicit "str(ModelClass)" that defeat the unicode problem. As far as I know, "__str__" shouldn't really be use but rather "__unicode__" to correctly handle string. Furthermore "str(ModelClass)" should be changed to "unicode(...)". After changing "str(...)" to "unicode(...)" it works in my use-case, but I haven't gone through all the code.
Would love to hear what your oppinion is.

**Comment by SerhiyRomanov** [comment]
My opinion is that you have to upgrade to Python 3.x as soon as possible)

**Comment by mauricioabreu** [comment]
I agree with @SerhiyRomanov
