### ISSUE TITLE
Pylint raises no-member

### ISSUE THREAD

**Issue by Horstage** [globocom/m3u8#242]
This code fails pylint review with pylint 2.7.0 (on Python 3.9).
```python
playlist = m3u8.load(playlist_path)
playlist.is_endlist
```
raises
`E1101: Instance of 'M3U8' has no 'is_endlist' member (no-member)`

I suppose it would happen with all [simple_attributes](https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L130).

**Comment by leandromoreira** [comment]
yes, given the dynamic nature of it

**Comment by Horstage** [comment]
Opened PR #243 as suggestion.

**Comment by leandromoreira** [comment]
Thanks @Horstage , I really appreciate your PR but I think it adds an implicit work, now everytime we want to add a new member, we need to do the usual mapping plus this proposed initialization (btw, it's NOT A big deal). 

Can't we just configure the `pylintrc` to assume that `m3u8` [has generated-members](https://docs.pylint.org/en/1.6.0/features.html)?

> generated-members:
>--
>  | List of members which are set dynamically and missed by pylint inference system, and so shouldn’t trigger E1101 when accessed. Python regular expressions are accepted.


```
generated-members=m3u8.*
``` 

I'm always trying to avoid adding code but I'd like to know @mauricioabreu @flavioribeiro @igorsobreira think about it as well.

**Comment by Horstage** [comment]
Yet another pylint config, I didn't know existed. Thanks!
I'm fine with this solution and do see why you would handle it this way.
For me, this issue is now resolved.

**Comment by mauricioabreu** [comment]
Sorry for taking so long. Well, yes, since this project does not have a pylintrc, you can edit your pylint configuration with @leandromoreira suggestion.
