### ISSUE TITLE
Parse Error when no #EXTINF

### ISSUE THREAD

**Issue by Creepercdn** [globocom/m3u8#244]
I'm try use m3u8 to parse a normal playlist, for example:
```
#EXTM3U
audio/music1.mp3
audio/ad.mp3
audio/music2.mp3
audio/misc.mp3
```
Example code:
```
import m3u8
playlist = m3u8.loads("#EXTM3U\naudio/music1.mp3\naudio/ad.mp3\naudio/music2.mp3\naudio/misc.mp3\n")
print(playlist.dumps())
```
`playlist.dumps()` will return `"#EXTM3U\n"`

**Comment by leandromoreira** [comment]
@Creepercdn your hls playlist/manifest is invalid and the [#EXT-X-INF](https://tools.ietf.org/html/rfc8216#section-4.3.2.1) is expected for variant playlist. This library covers only the [official tags and its specification](https://tools.ietf.org/html/rfc8216#section-1).

**Comment by Creepercdn** [comment]
This isn't a variant playlist. It just is a playlist, like a VLC playlist.

**Comment by leandromoreira** [comment]
@Creepercdn I see, this library was made to specifically handle [HLS playlists](https://tools.ietf.org/html/rfc8216#section-1).

**Comment by Creepercdn** [comment]
VLC playlist will export song info using #EXTINF, but no #EXTINF also will work. I think #EXTINF is not always need.

**Comment by leandromoreira** [comment]
It seems the tag is required.

```
4.3.2.1.  EXTINF

   The EXTINF tag specifies the duration of a Media Segment.  It applies
   only to the next Media Segment.  This tag is REQUIRED for each Media
   Segment.  Its format is:

   #EXTINF:<duration>,[<title>]

   where duration is a decimal-floating-point or decimal-integer number
   (as described in Section 4.2) that specifies the duration of the
   Media Segment in seconds.  Durations SHOULD be decimal-floating-
   point, with enough accuracy to avoid perceptible error when segment
   durations are accumulated.  However, if the compatibility version
   number is less than 3, durations MUST be integers.  Durations that
   are reported as integers SHOULD be rounded to the nearest integer.
   The remainder of the line following the comma is an optional human-
   readable informative title of the Media Segment expressed as UTF-8
   text.
```

**Comment by Creepercdn** [comment]
But no #EXTINF still works. I don't want to specified duration time, and I think sometimes do not need #EXTINF.
