### ISSUE TITLE
ValueError: could not convert string to float

### ISSUE THREAD

**Issue by drandreaskrueger** [globocom/m3u8#256]
I get an uncaught exception:

    ... m3u8/parser.py", line 241, in _parse_extinf
    state['segment']['duration'] = float(duration)
    ValueError: could not convert string to float: '-1 tvg-logo="https://i.imgur.com/3wQJsKQ.jpg" group-title="24/7 WORLD NEWS"'

when doing this

```
import m3u8
playlist = m3u8.load("file.m3u")
```

with this file.m3u:
```
#EXTM3U
#EXTINF:-1 tvg-logo="https://i.imgur.com/3wQJsKQ.jpg" group-title="24/7 WORLD NEWS",RT America
https://rt-usa.secure.footprint.net/1105.m3u8
```
which is from a standard IPTV file you find on the internet.

If that is a special problem with IPTV m3u files, then perhaps you could introduce some switch `m3u8.load(..., iptv=True)` which switches your parser into a different mode?

Or what am I doing wrong?

**Comment by SerhiyRomanov** [comment]
Currently, this library doesn't support parsing IPTV playlists. You can see some progress which I achieve to bring support of IPTV here https://github.com/globocom/m3u8/pull/247

**Comment by mauricioabreu** [comment]
Thank you @SerhiyRomanov
