### ISSUE TITLE
Add KEYID

### ISSUE THREAD

**Issue by girod2033** [globocom/m3u8#272]
Hello.

I got m3u8 with the following content:
"#EXT-X-KEY:METHOD=SAMPLE-AES-CTR,URI="data:text/plain;base64,AAAANnBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABYaB3RlbmNlbnQiC2EwMDQxbmswcmhs",KEYID=0xDBD23140D943E5B1F0860CAF3F181083,KEYFORMATVERSIONS="1",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed""

Please add output of "KEYID" value.
Thx.

**Comment by rokam** [comment]
I don't think that keyid is part of the standard.
https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming-16#section-4.3.2.4

You can extract it with a custom parser: https://github.com/globocom/m3u8/blob/master/README.rst#custom-tags

**Comment by girod2033** [comment]
> I don't think that keyid is part of the standard. https://datatracker.ietf.org/doc/html/draft-pantos-http-live-streaming-16#section-4.3.2.4
> 
> You can extract it with a custom parser: https://github.com/globocom/m3u8/blob/master/README.rst#custom-tags

Done, thanks again.
