### ISSUE TITLE
how to use for live stream mp2t format?

### ISSUE THREAD

**Issue by erickythierry** [globocom/m3u8#273]
hello, i have access to a streaming url which gives me a constant stream of chunked data in mp2t format.
ex: https://live.mydomain.com

if I put this url in a player like vlc, it opens the transmission normally. but I would like to make this stream url available in an m3u8 file. however I only find tools and tutorials that allow this from static files like mp4. could you tell me how to generate an m3u8 file that points to this live stream that I have?

**Comment by mauricioabreu** [comment]
Is this a public URL? Which kind of content does this URL have?

**Comment by mauricioabreu** [comment]
If you need more help, please, reopen the issue.
