### ISSUE TITLE
Support to get values for multiple EXT-X-MAP tags

### ISSUE THREAD

**Issue by Anjalivishnoi** [globocom/m3u8#276]
An HLS media playlist could have multiple number of EXT-X-MAP tags within media playlist but currently we could only retrieve one map tag's value via segment_map attribute of parsed m3u8.
The latter is pretty common usecase specially for CMAF content containing Discontinuous segments which may require multiple MAP tag's. The ask with this issue is to add support for getting a list of MAP tag's analogous to KeyList or SegmentList.

**Comment by mauricioabreu** [comment]
@Anjalivishnoi are you aware how EXT-X-MAP works, right? The one and only option I see here is to provide a method to get EXT-X-MAP for every segment. Are you okay with this solution?

**Comment by Anjalivishnoi** [comment]
@mauricioabreu : Yes that's right. 
It would be somewhat analogous to keys hence providing means to get list of maps for a parsed m3u8 similar to how it is done for keys(parsed_m38_obj.keys) would be really helpful. 

Along the same lines also check https://github.com/globocom/m3u8/issues/278 which i believe could be clubbed with this ask. 
Thanks for looking into this.

**Comment by mauricioabreu** [comment]
@Anjalivishnoi I'm working on it

**Comment by mauricioabreu** [comment]
Fixed via #279
