### ISSUE TITLE
Installation unter Libreelec?

### ISSUE THREAD

**Issue by Gorcon-user** [globocom/m3u8#281]
Hello, how to get this installed on Libreelec (Kodi)?

**Comment by mauricioabreu** [comment]
Hello @Gorcon-user I don't know what is Libreelec. Have you tried installing m3u8 through pip?

**Comment by rokam** [comment]
@Gorcon-user this is a library, it can be used by Kodi addons although it doesn't have an use directly with Kodi. As I know, there isn't a module addon to encapsulate this.

**Comment by mauricioabreu** [comment]
Thank you @rokam 

@Gorcon-user can we close this issue?

**Comment by Gorcon-user** [comment]
Yes
