### ISSUE TITLE
Add support to tag #EXT-X-IMAGE

### ISSUE THREAD

**Issue by darkbaboon** [globocom/m3u8#287]
Image Media Playlist for HLS (also known as Thumbnails) introduced a new tag #EXT-X-IMAGE in HLS Playlist.
Roku is one example of a platform that implements this specification which is located here:
[https://github.com/image-media-playlist/spec/blob/master/image_media_playlist_v0_4.pdf](https://github.com/image-media-playlist/spec/blob/master/image_media_playlist_v0_4.pdf)
This tag #EXT-X-IMAGE is not supported in Python m3u8 Parser.

**Comment by mauricioabreu** [comment]
I did not know about the existence of #EXT-X-IMAGE
Give me some time to read about it

**Comment by mauricioabreu** [comment]
Closed via #318
