### ISSUE TITLE
#EXT-X-KEY:MEATHOD=AES-128, unable to parse this tag

### ISSUE THREAD

**Issue by hecoter** [globocom/m3u8#298]
key: E8eSGRhvfWewxYq2vDNgYg==
m3u8url: https://secret.orthoday.com/secret/c8c5c46437dc446b9034186fcf8ca427/guoqingyundongyixue02.m3u8
method: AES-128-ECB

`import m3u8

m3u8url = 'https://secret.orthoday.com/secret/c8c5c46437dc446b9034186fcf8ca427/guoqingyundongyixue02.m3u8'
m3u8obj = m3u8.load(m3u8url)`

That's my code, when I use this package to parse this m3u8url, it occurred a error like this:
`TypeError: __init__() missing 1 required positional argument: 'method'`

Hope to solve this problem.

**Comment by bbayles** [comment]
The problem is the spelling of `METHOD`. It does not have an `A` character in it.

**Comment by mauricioabreu** [comment]
Thank you @bbayles

**Comment by hecoter** [comment]
He misspelled it on purpose to prevent parsing. Is there any way I can use it normally?

**Comment by mauricioabreu** [comment]
@hecoter who is "he"?
You can replace `MEATHOD` with `METHOD` and you are good to go

**Comment by hecoter** [comment]
如果将m3u8文件先下载下来，再去替换 `MEATHOD` 会导致`base_uri` 为空，我需要自己解析`base_uri`吗？是否有一个完整的示例可供参考？谢谢。

If I download the M3U8 file first, then replace `MEATHOD` will cause `base_uri` to be empty, do I need to parse `base_uri`? Is there a complete example for reference? thank you.

```
import m3u8
import requests

m3u8url = 'https://secret.orthoday.com/secret/c8c5c46437dc446b9034186fcf8ca427/guoqingyundongyixue02.m3u8'
response = requests.get(m3u8url).text
if '#EXT-X-KEY:MEATHOD' in response:
    response = response.replace('#EXT-X-KEY:MEATHOD','#EXT-X-KEY:METHOD')
with open('temp.m3u8','w',encoding='utf-8') as f:
    f.write(response)
m3u8obj = m3u8.load('temp.m3u8')

print(m3u8obj)
print(m3u8obj.base_uri) # base_uri 丢失
```

**Comment by leandromoreira** [comment]
you can always try to use your custom tag parser https://github.com/globocom/m3u8#custom-tags

**Comment by hecoter** [comment]
Problem solving,Thank you.
