### ISSUE TITLE
Can this program support multi thread downloading?

### ISSUE THREAD

**Issue by shutwin** [globocom/m3u8#299]
Can this program support multi thread downloading?

**Comment by rokam** [comment]
Hi, I don't see any benefits for multithreading support inside the lib. As the lib just downloads 1 file.
Maybe you can create threads before calling `m3u8.load(url)`:  https://docs.python.org/3/library/threading.html

**Comment by shutwin** [comment]
你好，我的意思是用咱们的模块来多线程下载 .ts 文件，而不是m3u8文件。直接调用模块来进行多线程下载.ts文件列表，这样更方便一些。

**Comment by bbayles** [comment]
[Here](https://gist.github.com/bbayles/d4df156ecbd4a162f279ed2f8465124e) is a script for multi-threaded downloading of TS files from an M3U8 playlist.

**Comment by mauricioabreu** [comment]
Moved to FAQ. 
Thank you @bbayles
