### ISSUE TITLE
How To Fix cqs Token At The m3u8 Link And Make The Link Permanent!

### ISSUE THREAD

**Issue by InsolenceWillow** [globocom/m3u8#312]
I Need Help Trying To Watch FX East On VLC With The m3u8, But The Link Keeps Changing! Here's The Link That I Tried Already: `https://content.uplynk.com/channel/31f3e230f9024bdbab19a28aa1799a18.m3u8?cqs=g0kpg5DofXwZazevRlo5RrBp9IwxCE0A4sR0FCIHPGPdsCSOi53sO5UP4J5IcnFQNTOeAmuMYALu4YB56qnjAfWtPppqZVdWuB6HJsyATOTtebqgshA5NoqAmawJswX1u9qh__WBCvfVWjOsQUaKJ3R5KbYym1mRQuTf3a1F_B9BDinQe8BOJVZcSRti3tm02TFBmpHshvkf0C2oF1zx5zUmh3rPs2gktunu2zXF_fwAqrWY3WlB0n0EpWtrfdOTdM8gL3sfbaTizRiFvuloTy2zAHDE_ATMkzuuh4_3snEfhTB3efAyZvXa2sHsbLx1_jbpebdETEvMHov-lVgABMWUsX_3H4lNiJJwYj34ZQcYVLM5k5GSU5Y0W-dupOv_ueY1VMBItOKG0A8_MjYLbRwo3riyrZ55DFIMl4aALjlh0PQAJJ_kfrQG2omPq431PCx8-uu5OZAyfN9DaCoE8Op1qxkrkDgnc7vgeGF_3QUEPdfbM_7WyCZpJYjUF8JDqSdlozptLwfoXlqv1CemNgiIkr-LPsYvMgkMR2mauyoPCsF7prNTl3hWnI7xPXys6wrZvhf5V-1S8lIiklJivGTxwRjamfVp0aJqQ2vrozQQcLM1MqW4tqIRK2c4Hx9f6eYVJVOwmnLcqLut3ryMVbeO054vq4OXs2DBFasWPQxFs7UEXcbp4kOqJyz34lMu4d9KmHa25BU4HcIuY0sMr0Z4XWwY7wYJ5fVtAcShFr4gJImVHQHs7VvoBs4BVbrDRueIleuX5ZHN5YqX6DUX5DuCDN0fGg8ypn27coBYZVgKijFSN2qySZy-C2ZVFoFzaUA9gj8i3oTixp2M5lKFQblYTsbfOWpWDFn4YnZOlDdrt284G2APPGfAE5hFf5lbj58xP9tI0XGk_E5CWiMXbq9bg_zHL18NUH0pvysXIGA8BqkBzii2ukugRVC-IGvhvTAvQdfnzbZFxtrOIKLZFcksUtviDf4SWJD3hMqad1FsaJC-LulefOu-uKnQfiKKqVsPTKtVvudq8aMmLEam863KMiS1VBYsAjlJ23Y3MQ8m9F0-sP1VpLDx9RZXU4pobtEmTczI6NygSyVnaPwzX5SV0w6S_q-EV5EJC7f_CLZJ1dMQQ0gwa2OPXCDCXbsB-XZzlf3X5lADJoKKJjSoKWwBZ7NvgYfAoXUr6I3pcXI6oWTBo1Eo7G0NVMXscjrd82v40ThFiq6QbK2omTQQOdLMy1-Go7a9Xbv70BXjtF97YsGnZ2pTsLptphLxdiMr-EByJ2kSEzyQiEQqNg3e3uT47BSLA8Ycv-d1ignAvTipUXeF-31KXLQcc_neHXePjkCDb60u4BBpOOtV-VMCb7Lxi6sM1WQX98Jk4DgLwuc3c1X2MEyjvkgkgx6CYPoIDgQrPIlYcVkrgSbWqW5I75z90DBlFu64mK5T7g19wSznc2D6Ht20I2kc_Xk-FIfcNxlM0qm3OwraxMfUvEn0MIU1SH7GHh1d7Dv6v3BNVN43FsS8i391_orNYUdR87d9I6K4j54SquW0sXmoulRQkLvWu87_RIFBulzmFsNeIZkGRAV3M3nF7tU-SsC0inUOHbThOOW20O8S9aLsLEK4ha6KliMJhi4VAG1xDbEYBHxbAfyc_A8aZjD00lU0CXcVX6Xy1HlkTqxjR83qXS3d6A==&kid=20c340c0afcb40d8974759757dd9cb44`

**Comment by leandromoreira** [comment]
this seems unrelated to the library usage
