### ISSUE TITLE
Inheriting from object class

### ISSUE THREAD

**Issue by semihartan** [globocom/m3u8#325]
Why do some classes inherit from the `object` class? It is the first time I ever saw that. Why is it required?

**Comment by AmirAli-Er** [comment]
hi 
for this question, I've found a great documentary
https://stackoverflow.com/questions/4015417/why-do-python-classes-inherit-object

**Comment by semihartan** [comment]
Hey thanks for your quick answer 😊

**Comment by AmirAli-Er** [comment]
your welcome🙂
