### ISSUE TITLE
installation broken.

### ISSUE THREAD

**Issue by robclemamzn** [globocom/m3u8#330]
The package needs clear working setup instructions.

currently i get:
 % ./setup.py 
./setup.py: line 1: from: command not found
./setup.py: line 3: from: command not found
./setup.py: line 5: long_description: command not found
./setup.py: line 6: syntax error near unexpected token `"README.rst"'
./setup.py: line 6: `if exists("README.rst"):'

**Comment by robclemamzn** [comment]
This seems to sidestep the problem for both modules iso8601 and m3u8

python -m pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver <your_package>

**Comment by nedmax** [comment]
Instructions by @bbayles worked for me. Created an wiki page: https://github.com/globocom/m3u8/wiki/Installing

**Comment by mauricioabreu** [comment]
Thank you @nedmax
