### ISSUE TITLE
Use built-in ISO 8601 parsing

### ISSUE THREAD

**Issue by daveisfera** [globocom/m3u8#331]
Continuing in the vein of #38, the [built-in parsing of ISO 8601 that was added in Python 3.7](https://docs.python.org/3/library/datetime.html#datetime.date.fromisoformat) should be used. This would require bumping the minimum supported Python version, but 3.8 is the oldest version that's still supported, so that should be a fine thing to do. I'd be glad to submit a PR for this, if it will be accepted

**Comment by bbayles** [comment]
One thing to consider: if you do performance profiling, you'll find that date parsing is one of the slowest things this library does. The `ciso8601` package is a C extension that speeds up this process greatly.

Right now it's easy to patch in `ciso8601` for `iso8601` (`m3u8.parser.cast_date_time = ciso8601.parse_datetime`).

I support dropping the `iso8601` dependency, but it would be good to maintain the ability to patch in `ciso8601`.

**Comment by daveisfera** [comment]
According to the [benchmarks on `ciso8601`](https://pypi.org/project/ciso8601/#toc-entry-5), it's a significant improvement over `iso8601` (almost 100x), but compared to the built-in function it's a lot closer, so the need to change that should go down a lot with this change and would still be completely possible

**Comment by daveisfera** [comment]
On a semi-related note, I added a [PR for adding 3.12](https://github.com/globocom/m3u8/pull/334) to the list of tested versions and I noticed that [`ciso8601` doesn't have wheel packages for that yet](https://github.com/closeio/ciso8601/issues/146), so it would need to be built from source until those are added

**Comment by movermeyer** [comment]
FWIW, there is also the option of using [`[backports.datetime_fromisoformat](https://github.com/movermeyer/backports.datetime_fromisoformat#backportsdatetime_fromisoformat)`](https://github.com/movermeyer/backports.datetime_fromisoformat), which brings Python 3.11's built-in parsing code to older versions of Python 3 (with pre-built wheels and high-performance).
