### ISSUE TITLE
M3u8 Support to be played in IPTV Player

### ISSUE THREAD

**Issue by naveenland4** [globocom/m3u8#348]
Hello,

Need your help in formation the attached movie. This type in plays well in Kodi but not playing in OTT Navigator, Tivimate, MX Player etc...

Could you please support me in this?

TIA
[Movie.txt](https://github.com/globocom/m3u8/files/13470474/Movie.txt)

**Comment by mauricioabreu** [comment]
Hello, @naveenland4 

What are you trying to do? Can you tell us what went wrong?
