### ISSUE TITLE
The method of calculating absolute_uri may be confusing. Adding a custom calculation method may be better.

### ISSUE THREAD

**Issue by xi-mad** [globocom/m3u8#352]
The absolute_uri property in BasePathMixin may not meet everyone's calculation needs. Would it be better to add the following custom calculation method?
![image](https://github.com/globocom/m3u8/assets/26453680/8e368ae6-cf96-4d50-8e4d-7b9938afc221)

**Comment by bbayles** [comment]
What is your use case?

**Comment by xi-mad** [comment]
Thank you for your reply. This is my mistake. I'm using another library that relies on m3u8, but it incorrectly sets the base_uri, leading me to believe there's an error in the m3u8 library's calculation.
