### ISSUE TITLE
'target_duration' returns float number, lead to iOS device fail to play the video

### ISSUE THREAD

**Issue by Scott0902** [globocom/m3u8#371]
The `target_duration` attribute in the `m3u8` library returns a float value, i.e.: 4.0, if I write a new playlist with tag `#EXT-X-TARGETDURATION: 4.0`, it will cause iOS devices fail to play the video. 

I discovered this bug by many attempts. Only by changing the `target_duration` to an integer resolves this issue, could allow iOS devices to play the video correctly.

I hope this m3u8 library to be modified to ensure the target_duration is always returned as an integer. This change will align the library with the HLS specification and ensure compatibility with iOS devices.

Thank you for your attention.

**Comment by mauricioabreu** [comment]
Hello @Scott0902 could you send a playlist example so we can reproduce this behavior?

**Comment by bbayles** [comment]
`EXT-X-TARGETDURATION` is indeed supposed to be an integer:
![image](https://github.com/user-attachments/assets/a15e866a-1db8-4f10-8635-99f92d379d0a)

The code currently calls [number_to_string](https://github.com/globocom/m3u8/blob/master/m3u8/model.py#L1650-L1658), which uses `to_integral_value` without a rounding specified. We could probably change it to use `ROUND_UP` for this particular value.

**Comment by mauricioabreu** [comment]
@bbayles agreed! But I still wanna understand how `target_duration` was converted to `4.0`.

Here is the specific part where `target_duration` is converted to a number.

```python
if self.target_duration:
            output.append(
                "#EXT-X-TARGETDURATION:" + number_to_string(self.target_duration)
            )
```

```sh
>>> import m3u8
>>> m3u8.model.number_to_string("4")
'4'
>>> m3u8.model.number_to_string("4.0")
'4'
>>> m3u8.model.number_to_string("3.9")
'3.9'
```

**Comment by Scott0902** [comment]
> Hello @Scott0902 could you send a playlist example so we can reproduce this behavior?

You can convert any H264-encoded `.mp4` video to `.ts` losslessly by using `ffmpeg.exe`, for example:

```
ffmpeg -i input.mp4 -c copy -bsf:v h264_mp4toannexb -f hls -hls_time 2 -hls_list_size 0 -hls_flags single_file -hls_segment_filename video.ts playlist.m3u8
```
By this way, `ffmpeg` will generate `playlist.m3u8` which is something like:

```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:5.005000,
#EXT-X-BYTERANGE:311140@0
video.ts
#EXTINF:5.005000,
#EXT-X-BYTERANGE:679244@311140
video.ts
#EXTINF:5.005000,
#EXT-X-BYTERANGE:525272@990384
video.ts
#EXTINF:10.427089,
#EXT-X-BYTERANGE:831712@1515656
...
#EXT-X-ENDLIST
```

With an integer value of `#EXT-X-TARGETDURATION`, Safari of iPhone is able to play the video correctly, but NOT when the value is a float value.

Since `m3u8.target_duration` would return a float value, if I use this library to concatenate some different mp4 videos and output a new playlist, Safari of iPhone would fail to play it.

**Comment by mauricioabreu** [comment]
@Scott0902 now I get it. Thank you! I'm going to fix it ASAP.

**Comment by mauricioabreu** [comment]
@Scott0902 it seem solve. If you think it is not, reopen the issue. Thank you!
