### ISSUE TITLE
MediaConvert EXT-CUE-OUT-CONT still problematic

### ISSUE THREAD

**Issue by wabiloo** [globocom/m3u8#373]
Hi,
I still have problems with some HLS manifests generated by AWS MediaConvert, even after the fix to #349.
Here is an example: https://bpkio-cs-demos.s3-eu-west-1.amazonaws.com/fabre/mediaconvert-conditioning/output/hls/cts-laworder720p.m3u8

The lib fails on this line:
`#EXT-X-CUE-OUT-CONT:10/4, SpliceType=VOD_DAI,Action=REPLACE,PAID=amazon.com/TEST2014020500000346,Acds=BA`.

Note that this type of markup is coming straight from the (poor) AWS documentation at https://docs.aws.amazon.com/mediaconvert/latest/ug/example-esam-xml-manifest-conditioning.html

**Comment by bbayles** [comment]
I'll take a shot at fixing this!
