### ISSUE TITLE
EXT-X-BITRATE parsing returns value as string rather than int

### ISSUE THREAD

**Issue by davemevans** [globocom/m3u8#376]
[EXT-X-BITRATE](https://datatracker.ietf.org/doc/html/draft-pantos-hls-rfc8216bis#section-4.4.4.8) is defined as a decimal integer describing the rate in kilobits per second.

Currently the parser will return this value [as a string](https://github.com/globocom/m3u8/blob/master/tests/test_parser.py#L859) which is awkward when working with this value.

I have a simple patch to parse and dump this as an int but it would technically be a small breaking change.

What do people think?

**Comment by mauricioabreu** [comment]
@davemevans submit your PR, please. If it follows the spec, I'll gladly accept it. We can upgrade the major.

**Comment by mauricioabreu** [comment]
Closed via #379
