### ISSUE TITLE
invalid literal for int()

### ISSUE THREAD

**Issue by yunsonbai** [globocom/m3u8#378]
if #EXTINF:12.96,  will be load erro: invalid literal for int()

**Comment by mauricioabreu** [comment]
@yunsonbai please, paste your HLS manifest here so we can use it as an input for a test case.

**Comment by leandromoreira** [comment]
<img width="649" alt="image" src="https://github.com/user-attachments/assets/dbb3b393-1911-49cc-913d-fa6378f19d05">
I believe when the manifest contains a floating point, the `int` function wont work.

**Comment by mauricioabreu** [comment]
Thank you @leandromoreira

**Comment by mauricioabreu** [comment]
Well, there are many tests with manifests that contain floating point numbers in `EXTINF`.
@yunsonbai do you mind sharing an example of manifest?
Which m3u8 version are you using?

**Comment by yunsonbai** [comment]
@mauricioabreu I'm sorry，this should be an issue with the file I am using, as it does not comply with the specifications and caused an exception. So this issue can be closed.

**Comment by mauricioabreu** [comment]
@yunsonbai that's ok! Thank you for getting back.
