### ISSUE TITLE
There is no way to get the EXT-X-AGORA-TRACK-EVENT: EVENT, TRACK_TYPE, TIME from the playlist.

### ISSUE THREAD

**Issue by rjsnh1522** [globocom/m3u8#381]
Hi,
I am working with agora and it gives me some audio video files with m3u8 files too.
I am using your package to find some details.
The details I am looking for is 
`#EXT-X-AGORA-TRACK-EVENT:EVENT=START,TRACK_TYPE=AUDIO,TIME=20240910090123736`
but there is no way to do it from you package.

here is the sample m3u8 file

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-TARGETDURATION:18
#EXT-X-AGORA-TRACK-EVENT:EVENT=START,TRACK_TYPE=AUDIO,TIME=20240910090123736
#EXTINF:15.010000
2967baa4c74980d1280bb185ae526094_K0wLZk45v__uid_s_259__uid_e_audio_20240910090123736.ts
#EXTINF:15.020000
2967baa4c74980d1280bb185ae526094_K0wLZk45v__uid_s_259__uid_e_audio_20240910090138746.ts
#EXTINF:15.020000
2967baa4c74980d1280bb185ae526094_K0wLZk45v__uid_s_259__uid_e_audio_20240910090153766.ts
#EXTINF:9.940000
2967baa4c74980d1280bb185ae526094_K0wLZk45v__uid_s_259__uid_e_audio_20240910090208786.ts
#EXT-X-ENDLIST
```

is there any way to get this data, I am looking for track type and the time data.
Thanks

**Comment by rjsnh1522** [comment]
This can be done using custom parser, but native support would have been better.
Closing this issue.
will try to make a native fix and raise an MR

**Comment by mauricioabreu** [comment]
Hello @rjsnh1522,

This appears to be a custom tag, and we will likely reject your PR unless it’s widely used within the community. Adding arbitrary custom tags would make the parser unnecessarily bloated.

**Comment by rjsnh1522** [comment]
Didn't knew its a custom tag.
It is coming from Agora  for video and audio recording.

Anyways thanks for prompt response
