### ISSUE TITLE
Incorrect child absolute_uri values generated from base_uri.

### ISSUE THREAD

**Issue by GrumpyOldTroll** [globocom/m3u8#42]
Passing the original url as the base_uri input parameter to M3U8 constructor (as the description in its help text describes) makes incorrect absolute_uri paths for the child objects.

This code exercises the problem against one of Apple's sample streams:
```
$ python
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2, m3u8, urlparse
>>> url='https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8'
>>> text=urllib2.urlopen(url).read()
>>> m=m3u8.M3U8(content=text, base_uri=url)
>>> m.playlists[0].absolute_uri
'https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8/gear1/prog_index.m3u8'
```

My expectation is that m.playlist[0].absolute_uri would be "https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8", as you would get from urlparse.urljoin, which is the actual location of the playlist that a video player would retrieve (a relative path derived from the original uri, NOT a sub-path of the original uri). Continuing on, that url that I was expecting does in fact succeed:

```
>>> urlparse.urljoin(url, m.playlists[0].uri)
'https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear1/prog_index.m3u8'
>>> subtext=urllib2.urlopen(urlparse.urljoin(url, m.playlists[0].uri)).read()
>>> len(subtext)
6701
>>> sub_m=m3u8.M3U8(subtext)
>>> len(sub_m.segments)
181
```

Whereas the absolute_uri from the playlist fails:
```
>>> m.playlists[0].absolute_uri
'https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8/gear1/prog_index.m3u8'
>>> m.playlists[0].uri
'gear1/prog_index.m3u8'
>>> subtext=urllib2.urlopen(m.playlists[0].absolute_uri)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
```

For reference, in case it goes down or changes, the present contents of that master playlist url are here:
```
#EXTM3U


#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=232370,CODECS="mp4a.40.2, avc1.4d4015"
gear1/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=649879,CODECS="mp4a.40.2, avc1.4d401e"
gear2/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=991714,CODECS="mp4a.40.2, avc1.4d401e"
gear3/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=1927833,CODECS="mp4a.40.2, avc1.4d401f"
gear4/prog_index.m3u8

#EXT-X-STREAM-INF:PROGRAM-ID=1,BANDWIDTH=41457,CODECS="mp4a.40.2"
gear0/prog_index.m3u8

```

**Comment by GrumpyOldTroll** [comment]
It's possible to work around this issue with something like:
```
def _trim_url_tail(url):
    us = urlparse.urlsplit(url)
    change_to = us[:2] + (posixpath.dirname(us[2]),) + us[3:]
    return urlparse.urlunsplit(change_to)

m=m3u8.M3U8(content=text, base_uri=_trim_url_tail(url))
```

But it seems more awkward than probably was intended, I'm guessing?

Would you accept a fix for this which just changes the semantics of base_uri (and the associated tests), or would it be necessary to add a new parameter, like source_uri, which would behave this way (leaving base_uri alone for backward compatibility)?

**Comment by leandromoreira** [comment]
@GrumpyOldTroll Although I agree it is awkward, I think if this fixes the issue, okay. What you guys think @jbochi @flavioribeiro @hltbra @lucasmundim @danielfm ?

**Comment by danielfm** [comment]
Actually I don't find that awkward at all...

**Comment by leandromoreira** [comment]
@GrumpyOldTroll can you make a PR with that solution?

**Comment by GrumpyOldTroll** [comment]
I have evolved my solution slightly, but I think nearly equivalently. I encountered another problem, for which the proposed solution still had a similar problem, with http://hls.ted.com/talks/2297.m3u8. Here I see non-url absolute paths such as "/talks/2297/subtitles/en.m3u8" inside the master m3u8, which given a base url of "http://hls.ted.com/talks/2297.m3u8" should resolve to "http://hls.ted.com/talks/2297/subtitles/en.m3u8". This matches urlparse.urljoin behavior, so I've switched to using urlparse.urljoin.

To preserve backward compatibility with other cases, I've hacked it a slightly simpler way, by appending '/' to _base_uri if it doesn't end in '/'. This keeps the prior appending behavior the same when using relative paths (and continues to require callers to strip off the final part of the path). I had to change one test case's behavior, which I argue would not be desirable behavior whenever the absolute_uri is used to download from a netloc. All the other test cases were preserved.

The changed test was here:
https://github.com/globocom/m3u8/blob/01fdd66609d866938b54db48de39528b1594a8e8/tests/test_loader.py#L71
Regarding playlist: https://github.com/globocom/m3u8/blob/01fdd66609d866938b54db48de39528b1594a8e8/tests/playlists/relative-playlist.m3u8, with base_url "http://localhost:8112/path/to", applied to the path "/entire1.ts". The prior behavior was that the corresponding absolute_uri resolves to "http://localhost:8112/path/to/entire1.ts" and the new behavior is that absolute_uri resolves to "http://localhost:8112/entire1.ts".
