### ISSUE TITLE
Comments are not preserved through loads() + dumps()

### ISSUE THREAD

**Issue by GrumpyOldTroll** [globocom/m3u8#44]
The hls spec permits comments (c.f. https://tools.ietf.org/html/draft-pantos-http-live-streaming-16#section-4.1, 3rd paragraph).

Some tools use comments to provide extensions to compatible players (such as brightcove zencoder). Preserving comments in their proper locations would interoperate better with such tools.

Here's an example of a playlist with a brightcove-like comment, and which fails the test_dumps_should_build_same_string test:

```
PLAYLIST_WITH_COMMENT = '''
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-TARGETDURATION:8
#EXTINF:8,
http://media.example.com/entire.ts
#ZEN-TOTAL-DURATION:8
#EXT-X-ENDLIST
'''
```

(This example also fails because VOD and TARGETDURATION get reordered, a separate issue.)

**Comment by mauricioabreu** [comment]
@leandromoreira I think the new `custom_tags_parser` function can solve this issue too. Right?

**Comment by leandromoreira** [comment]
@mauricioabreu yes but @GrumpyOldTroll should to implement a parser for it since there is not an optional parser PARSE IT ALL into namedtuple or something else

**Comment by mauricioabreu** [comment]
@leandromoreira comments were not being preserved because they were being ignored by the parse. If users want to retrieve the comments and populate the `data` with them, now they can. But I got you said. There is no way to parse it all into another structure in a fashion way.

**Comment by leandromoreira** [comment]
In the end, it closes this issue too, impressive on PR closes many issues. Thanks.
