### ISSUE TITLE
Segment.__str__() causes TypeError

### ISSUE THREAD

**Issue by gabrielfalcao** [globocom/m3u8#57]
calling `str(segment)` causes `TypeError` because the `Segment.dumps` method requires an argument.
This issue is similar to #56

**Comment by leandromoreira** [comment]
@gabrielfalcao hey can you check it again? I think this PR https://github.com/globocom/m3u8/pull/65 solved the issue.

**Comment by leandromoreira** [comment]
I'm gonna close this one, @gabrielfalcao if you notice that https://github.com/globocom/m3u8/pull/65 didn't solve your case I'll be happy to reopen this.
