### ISSUE TITLE
How to handle encryption

### ISSUE THREAD

**Issue by audetto** [globocom/m3u8#67]
Hi,

I've been using this m3u8 library to download .m3u8 files.
Now I found one with encryption

http://lb.cdn.m6web.fr/s/cu/prime/vod/protected/7/e/b/Enquete-exclusive_c11529756_Daesh-la-multinat/Enquete-exclusive_c11529756_Daesh-la-multinat_400k.mp4.m3u8

the top looks like this

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:7
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-FAXS-CM:URI="Enquete-exclusive_c11529756_Daesh-la-multinat_400k.mp4.drm"

#EXT-X-KEY:METHOD=AES-128,URI="faxs://faxs.adobe.com",IV=0x5a8ddab79f4fff6a8333ea8ff64d3cd4
#EXT-X-MEDIA-TIME:0.0
#EXTINF:6,
Enquete-exclusive_c11529756_Daesh-la-multinat_400k.mp4.0_6000.ts?trackid=1,2

I can download the .drm which seems to be related to Flash.
I can download the individual pieces, but they seem to be encrypted.
Anybody knows how the process works?

**Comment by leandromoreira** [comment]
http://docs.aws.amazon.com/elastictranscoder/latest/developerguide/content-protection.html

https://support.brightcove.com/en/video-cloud/docs/protecting-videos-devices-hls-encryption

**Comment by audetto** [comment]
that is a start.
have you got any experience with it?
I am a bit worried about the URI

URI="faxs://faxs.adobe.com"

**Comment by besweeet** [comment]
Any progress on this?

**Comment by bertothunder** [comment]
@audetto the URI for the key is managed by Adobe DRM in Flash. The player recognizes the URI format to obtain the key data from Adobe DRM system.

Do I assume right that you are trying to unencrypt the content to play it?

**Comment by audetto** [comment]
Yes,

Is there any chance to do it?

**Comment by bertothunder** [comment]
@audetto to do what? unencrypt the content? manage the Adobe DRM URI? It's out of scope for a m3u8 parser, not to mention it breaks a copyrighted DRM and goes against the law.

**Comment by audetto** [comment]
I am not expecting this project to do it,

but as there are a lot of people with experience on m3u8 playlist, someone might have found similar cases and could point me to a web source where such a process is described.

**Comment by bertothunder** [comment]
You should google for it, but I sincerely doubt you'll find anything on it. DRM encryption is tough unless a key leakage is found.

@leandromoreira IMHO the issue can be safely closed, what do you think?
