### ISSUE TITLE
Ignore blank lines in m3u8 file

### ISSUE THREAD

**Issue by generalash** [globocom/m3u8#68]
I came across a stream with blank lines in the m3u8 file, between each stream info line and uri. In the protocol for these files, it states the blank lines should be ignored. When I ran the parser on it though the uri was being set as an empty string. If I add the following to the for loop in the parse function (in parser.py) it ignores these lines:

`# Ignore blank lines`
` if line == "":`
`continue`

In the HTTP live streaming protocol internet draft, the following appears in section 4.1 Definition of a playlist:
"Each line is a URI, blank, or starts with the character '#'.  Blank lines are ignored."

See the document here:
https://tools.ietf.org/html/draft-pantos-http-live-streaming-18#section-4.1

Is this a reasonable thing for me to submit a patch for?

**Comment by leandromoreira** [comment]
go ahead @generalash lol
