### ISSUE TITLE
EXTINF tag with optional comma?

### ISSUE THREAD

**Issue by ziima** [globocom/m3u8#73]
m3u8 library requires EXTINF tag to have title, but the title is optional, see https://tools.ietf.org/html/draft-pantos-http-live-streaming-09#section-3.3.2

**Comment by ziima** [comment]
I stand corrected, the comma is required. The problem is I get playlists where the comma is missing. Can we make it optional?

**Comment by leandromoreira** [comment]
> https://tools.ietf.org/html/draft-pantos-http-live-streaming-19#section-4.3.2.1

```
   The EXTINF tag specifies the duration of a Media Segment.  It applies
   only to the next Media Segment.  This tag is REQUIRED for each Media
   Segment.  Its format is:

   #EXTINF:<duration>,[<title>]

   where duration is a decimal-floating-point or decimal-integer number
   (as described in Section 4.2) that specifies the duration of the
   Media Segment in seconds.  Generally, durations SHOULD be decimal-
   floating-point, with enough accuracy to avoid perceptible error when
   segment durations are accumulated.  If the compatibility version
   number is less than 3, durations MUST be integers.  Durations that
   are reported as integers SHOULD be rounded to the nearest integer.
   The remainder of the line following the comma is an optional human-
   readable informative title of the Media Segment expressed as raw
```

**The remainder of the line following the comma is an optional human-**
**readable informative title of the Media Segment expressed as raw**

Does it mean, comma is required? is it what follows aka title?

When I see the pattern `#EXTINF:<duration>,[<title>]` I think `,` is mandatory, what are you thoughts?

**Comment by ziima** [comment]
It looks like the specification defines comma as required. But I ran into playlists which lacks the commas, which complicates usage of the m3u8 parser.

Maybe we can allow comma to be missing, possibly according to some `strict` parameter. That would also match common principle "Be strict in what you send, but generous in what you receive".

**Comment by leandromoreira** [comment]
@ziima I think it's okay, since it's a option maybe by the main entry point `m3u8.load(url, options)`
