### ISSUE TITLE
Custom HTTP Headers

### ISSUE THREAD

**Issue by PhilippeR** [globocom/m3u8#82]
Hi,
Is it possible to customize request HTTP Headers ?  
Tks.
Philippe

**Comment by leandromoreira** [comment]
I'm sorry, can you give an example of what you want to do?

**Comment by PhilippeR** [comment]
Add custom http headers or override standard HTTP header like user Agent in http request.
We can imagine m3u8_obj=m3u8.load(value, headers) 

Exemples: 
X-Playback-Session-Id: 8ECAD943-8CC6-40B5-8550-E64EE579BB0D
X-MYCUSTOM-HEADER: Let's Go
Connection: keep-alive
Accept: */*
User-Agent: AppleCoreMedia/1.0.0.14A456 (iPad; U; CPU OS 10_0_2 like Mac OS X; fr_fr)
Accept-Language: fr-fr
Accept-Encoding: identity
Connection: keep-alive

**Comment by leandromoreira** [comment]
It isn't possible to this now but it sounds like a fair feature and it needs to be [compatible for p2 and p3](https://github.com/globocom/m3u8/tree/master/m3u8#L13-L19).

```
# this solves the issue while we're using urllib2
import urllib2
request = urllib2.Request("http://www.google.com", headers={"Accept" : "text/html"})
contents = urllib2.urlopen(request).read()
```

**Comment by PhilippeR** [comment]
Thanks ;-)
Believe me, It makes sense to choose them sometimes.,

**Comment by mauricioabreu** [comment]
Support for `custom headers` was added in #95 
Closing.
