### ISSUE TITLE
Any way to get the video byte size an m3u8 url referenced to ?

### ISSUE THREAD

**Issue by redstoneleo** [globocom/m3u8#92]

**Comment by leandromoreira** [comment]
I think you can get that by looking at the response header `content-length` but then you need to either download the chunk or issue a `HEAD` request. While I was searching through the [official documentation](https://tools.ietf.org/html/draft-pantos-http-live-streaming-20), I couldn't find any metadata with this information.

And specifically in this lib you could change this request to delivery the size for each request https://github.com/globocom/m3u8/blob/master/m3u8/__init__.py#L73-L77 but then you could do that by only looking at the binary segment.

**Comment by redstoneleo** [comment]
While I was searching through the official documentation, I find this relevant 

>  The average segment bit rate of a Media Playlist is the sum of the
>    sizes (in bits) of every Media Segment in the Media Playlist, divided
>    by the Media Playlist duration. 

so  the sum of the  sizes (in bits) of every Media Segment is equal to the Media Playlist duration times the average segment bit rate.
I just don't know if this lib could actually return the Media Playlist duration and the average segment bit rate for an m3u8 url

**Comment by mauricioabreu** [comment]
I'm closing this because it is something that we believe that should be achieved out of this lib. If you are not okay with this, please, reopen.
