### ISSUE TITLE
Add the ability to set headers for URI

### ISSUE THREAD

**Issue by baco** [globocom/m3u8#94]
Some sites require setting some headers like ``Referer`` or ``Cookie``, even the ``UserAgent`` sometimes, to access the the content and don't be filtered by the webserver. Using ``m3u8.load()`` won't allow you to setup anything of the sort.

Of course, it is possible to bypass the issue by making the request by hand using ``urllib.request`` module and then ``m3u8.loads()`` but it adds extra  complexity and the resulting m3u8 objects (playlists or segments) lack of some attributes like ``.absolute_uri`` then.

One possible solution is to add an extra argument to ``m3u8.load()``, for example ``headers={}``, and when set to anything different than that, make the request using ``Request()`` and then ``urlopen()`` inside the ``m3u8.load()`` method.

**Comment by leandromoreira** [comment]
Hi @baco thank you for commenting, so what do you really want to have is the ability to add `header` for all the requests?

**Comment by baco** [comment]
Yes, sorry; I've asked for `data` field but `header` was the one I am needing right now. I am updating the issue in accordance.

**Comment by leandromoreira** [comment]
@baco I'll close this one since it's the same as https://github.com/globocom/m3u8/issues/82 do you agree?

**Comment by baco** [comment]
Agreed ☺️
